YELLOW="\[\033[0;33m\]"
CLEAR="\[\033[0m\]"
RED="\[\033[0;31m\]"
BLUE="\[\033[0;36m\]"
ORANGE="\[\033[0;91m\]"
PS1="$BLUE\u$CLEAR in $YELLOW[$ORANGE\w$YELLOW]$RED » $CLEAR"

export CLICOLOR=1

alias stagr="sudo stagr"